DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS usersSalt;

CREATE TABLE users(
	  userID INT UNSIGNED PRIMARY KEY AUTO_INCREMENT
    , username VARCHAR(256) NOT NULL
    , firstname VARCHAR(256) NOT NULL
    , lastname VARCHAR(256) NOT NULL
    , email VARCHAR(256) NOT NULL
    , pass VARCHAR(256) NOT NULL
);

CREATE TABLE usersSalt(
	  userID INT UNSIGNED PRIMARY KEY
	, userSalt VARCHAR(256) NOT NULL
    , userKey VARCHAR(256) NOT NULL
);

ALTER TABLE users AUTO_INCREMENT=1000;